### ISSUE TITLE
Cannot get BLE keyboard to "connected"

### ISSUE THREAD

**Issue by PaeP3nguin** [jum0n/vavaEsphomeRemotePower#1]
Hey there, thank you for the excellent instructions. I was able to get an ESPHome device to register as "Paired" but for the life of me I can't get it to "Connected" even after several power cycles of the projector and ESPHome device. Any ideas on how to debug or tips on getting this to work?

**Comment by jum0n** [comment]
The only advice I can give is to try many times.  It took me at least 10-15 tries (with projector shutdown/unplug/boot up) before it "connected" for me.  Once it did, though, it has been stable ever since.  I'll leave this open and hopefully someone else might have other suggestions.

**Comment by PaeP3nguin** [comment]
Thank you for the advice. In the ended I wired up a HDMI breakout box to turn off the projector, that seems to be working fairly reliably (though with a strange hiccup of needing the Chromecast to be on and selected as the input): https://www.reddit.com/r/homeautomation/comments/1b4y5et/comment/l0c77v9/
